### ISSUE TITLE
Any plan to update to 11.1.2?

### ISSUE THREAD

**Issue by maxdd** [wyattearp/ghidra_uf2loader#4]
I'm getting this on 11.1.2

```
'void ghidra.app.util.bin.BinaryReader.setPointerIndex(long)'
java.lang.NoSuchMethodError: 'void ghidra.app.util.bin.BinaryReader.setPointerIndex(long)'
	at uf2loader.uf2loaderLoader.populateBlock(uf2loaderLoader.java:279)
	at uf2loader.uf2loaderLoader.findSupportedLoadSpecs(uf2loaderLoader.java:146)
	at ghidra.app.util.opinion.LoaderService.getSupportedLoadSpecs(LoaderService.java:47)
	at ghidra.app.util.opinion.LoaderService.getAllSupportedLoadSpecs(LoaderService.java:71)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:286)
	at ghidra.plugin.importer.ImporterUtilities.showImportDialog(ImporterUtilities.java:154)
	at ghidra.plugin.importer.ImporterUtilities.lambda$showImportDialog$0(ImporterUtilities.java:106)
	at ghidra.util.task.TaskLauncher$2.run(TaskLauncher.java:117)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

i think the new method is 

`long setPointerIndex(long index)`

**Comment by wyattearp** [comment]
@maxdd - I didn't have any plan to do it as this was a "one off" I built just to learn; but I can take a note to check this coming weekend. Happy to take a PR if you have one already.
